### ISSUE TITLE
zlib update?

### ISSUE THREAD

**Issue by Neustradamus** [4kills/zlib#13]
Dear @4kills,

Can you update your code with the current original zlib code?
- https://github.com/madler/zlib
- https://github.com/madler/zlib/releases
- https://zlib.net/

Thanks in advance.

**Comment by haveachin** [comment]
This package uses the native zlib library installed on your system. What do you mean by update your code? Has the zlib API changed?

**Comment by 4kills** [comment]
No further information given and stale. Perhaps the OP used an old version of this project, before we switched to using the installed zlib version, or the zlib version on OP's system is outdated.

**Comment by Neustradamus** [comment]
CVEs are not impacted?

**Comment by 4kills** [comment]
Since [CVE-2023-45853](https://nvd.nist.gov/vuln/detail/CVE-2023-45853) was fixed with zlib release 1.3.1 there is no need for us to act. This library is just a wrapper around whatever version of zlib is installed on the user's system. If a user still has the compromised version 1.3.0 installed, there is nothing we can do by updating our wrapper. Thank you very much for bringing this to our attention though!
